# Generated by Django 3.1 on 2020-08-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('prioridade', models.IntegerField(choices=[(0, 'Caso Geral'), (1, 'Gestante'), (2, 'Idoso'), (3, 'Encaminhado Pelo Medico')])),
            ],
        ),
    ]
